###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###
GET http://localhost:3000/user/tweets/feed/
Content-Type: application/json
###
GET http://localhost:3000/user/following/
Content-Type: application/json
###
GET http://localhost:3000/user/followers/
Content-Type: application/json
###
GET http://localhost:3000/tweets/4/
Content-Type: application/json
###
GET http://localhost:3000/tweets/4/likes/
Content-Type: application/json
###
GET http://localhost:3000/tweets/4/replies/
Content-Type: application/json
###
GET http://localhost:3000/user/tweets/
Content-Type: application/json
###
DELETE http://localhost:3000/tweets/2/
Content-Type: application/json